### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by fitojb** [linusbobcat/create-elementary-os-installer#1]
There seems to be no support for adding translations for this application to use, in order to be useful in non-English systems.

**Comment by linusbobcat** [comment]
Thanks! I will look into this.

**Comment by linusbobcat** [comment]
Thanks for your post. I've added initial support for internationalization. Currently only English is supported but I'll ping the Google Plus community to try to get translations. 

If you want to help with translations in your own language, find out what [your language code is](http://loc.gov/standards/iso639-2/php/code_list.php) and start editing the translation folder at _"Create elementary OS Installer/Contents/Resources/en.lproj/Localization.strings". Replace "en.lproj" with your own language code. You *do not_ need OS X. Make sure the "localization.strings" file is encoded in utf-16. 

I'm going to close this issue, but if any issue arrives don't hesitate to comment here.

**Comment by fitojb** [comment]
Cool, thanks a lot!
