### ISSUE TITLE
Fails if no Downloads folder

### ISSUE THREAD

**Issue by 19wolf** [linusbobcat/create-elementary-os-installer#26]
I ran into the issue where the applet fails completely if there is no Downloads folder present. My setup includes having my Downloads folder on a Transcend JetDrive, and when I went to make a boot SD Card, I had to remove it.

I fixed the problem by adding a "try" clause in the setting downloads folder, which works fine.

```
try
    set downloadsFolder to (path to home folder as text) & "Downloads" as alias
on error
    set downloadsFolder to (path to home folder as text) as alias
end try
```

I've never used Git, so I don't know how to actually create a pull request or anything.

**Comment by linusbobcat** [comment]
Thanks for the report. I'll make and push out the update soon.
