### ISSUE TITLE
Crashes on Mac OS X Lion and below

### ISSUE THREAD

**Issue by gobr4ga** [linusbobcat/create-elementary-os-installer#27]
That's the report generated by the system:

Process:         launchd [8910]
Path:            /Users/USER/Downloads/*/Create elementary OS Installer.app/Contents/MacOS/applet
Identifier:      com.apple.ScriptEditor.id.Create-elementary-OS-Installer
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [233]

Date/Time:       2016-01-13 05:14:40.700 -0200
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1021936 sec
Crashes Since Last Report:           13
Per-App Crashes Since Last Report:   13
Anonymous UUID:                      D25D88B1-F918-4A92-89EB-3E88A3FEBE59

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1981
    thread_create: 0
    thread_set_state: 0

Model: MacBook4,1, BootROM MB41.00C1.B00, 2 processors, Intel Core 2 Duo, 2.4 GHz, 6 GB, SMC 1.31f1
Graphics: Intel GMA X3100, GMA X3100, Built-In, 144 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F7F7F7F3400, 0x4D4120543636375342344730312D53545420
Memory Module: BANK 1/DIMM1, 2 GB, DDR2 SDRAM, 667 MHz, 0x7F98000000000000, 0x202020202020202020202020202020202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x88), Broadcom BCM43xx 1.0 (5.10.131.36.15)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Corsair Force GS, 360,08 GB
Parallel ATA Device: HL-DT-ST DVDRW  GSA-S10N
USB Device: USB Drive, 0x090c  (Silicon Motion, Inc. - Taiwan), 0x1000, 0xfd100000 / 3
USB Device: Built-in iSight, apple_vendor_id, 0x8501, 0xfd400000 / 2
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0229, 0x5d200000 / 3
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0x5d100000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8205, 0x1a100000 / 2

**Comment by linusbobcat** [comment]
Thanks for the report.

First, I'd like to mention that your MacBook is old enough that it probably won't be able to boot elementary OS (or any Linux) from a USB drive using this tool, not even from rEFInd/et. I would recommend creating a DVD installer instead or using the Mac Linux USB Loader which does some magic to make Linux USB booting work on older Macs.

Could you try opening the app in AppleScript/Script Editor and then try to run it? I'll post the source code in a plain text file as soon as I'm able to do so if the app won't open. It might look like I'll have to compile the AppleScript on Snow Leopard in order to ensure backwards and forward compatibility.

Although I wouldn't recommend USB booting using this tool, if you still want to try, your options are to get access to a newer version of OS X, or follow a tutorial online for creating Ubuntu USB installers that involves terminal commands that uses "dd". I do not recommend using UnetBootin.

(Note to self: auto detect unsupported Macs in the future.)

**Comment by gobr4ga** [comment]
Hi linusbobcat, thanks for the feedback. I had already considered that possibility. Unfortunately Lion 10.7.5 is the latest version of Mac OS compatible with this Macbook.

When trying to run the App in Apple Script Editor, returns the following:
Syntax Error
Can’t set «class ppgt» to 3. Access not allowed.
![screen shot 2016-01-13 at 07 06 46](https://cloud.githubusercontent.com/assets/16680429/12289738/3fcd88d2-b9c4-11e5-94ad-bab51e42cdf8.png)

**Comment by linusbobcat** [comment]
Removing the weird `set <<class ppgt>` should make it to work. Here's how the proper script should work: https://gist.github.com/linusbobcat/a51f1ab06770746817e5

It looks like I'll have to end up compiling the initial Applescript on Mac OS X Snow Leopard in order for it to be backwards-compatible, although getting access to it will be difficult.

Could you try downloading an older version (0.2.4) and tell me whether that works or not?

**Comment by linusbobcat** [comment]
If somehow could confirm this, that would be great. I'll mark this incomplete for now.

**Comment by gobr4ga** [comment]
Sorry for the delay. Follows the error returned. The version 0.2.4 don't work too.
![screen shot 2016-01-28 at 10 03 00](https://cloud.githubusercontent.com/assets/16680429/12644094/94b36364-c5a7-11e5-8518-8b7edfa05798.png)

**Comment by sysfu** [comment]
Reproduced the same issue on Snow Leopard 10.6.8. If you need remote access to my system for testing let me know.

**Comment by linusbobcat** [comment]
Thanks for helping to debug. Could you guys try opening v0.2.4 in Applescript and try running it? Also, how does v0.2.4 fail? 

Edit: I might have found the culprit. Apparently Applescripts in Yosemite and higher don't run on Lion. Once I have access to my computer I'll create one with Mavericks and put it here for you guys to try out.

**Comment by gobr4ga** [comment]
v0.2.4 on Lion 10.7.5

Running from Apple Script, apparently there are no problems, but when trying to run the app usually returns the following error:

`Process:         launchd [383]
Path:            /Users/USER/Downloads/*/Create elementary OS Installer.app/Contents/MacOS/applet
Identifier:      com.apple.ScriptEditor.id.Create-elementary-OS-Installer
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [218]

Date/Time:       2016-01-29 21:38:47.114 -0200
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          154914 sec
Crashes Since Last Report:           25
Per-App Crashes Since Last Report:   17
Anonymous UUID:                      FA3383DC-C253-40B1-AE6A-DDF8206D40EE

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 412
    thread_create: 0
    thread_set_state: 0

Model: MacBook4,1, BootROM MB41.00C1.B00, 2 processors, Intel Core 2 Duo, 2.4 GHz, 6 GB, SMC 1.31f1
Graphics: Intel GMA X3100, GMA X3100, Built-In, 144 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F7F7F7F3400, 0x4D4120543636375342344730312D53545420
Memory Module: BANK 1/DIMM1, 2 GB, DDR2 SDRAM, 667 MHz, 0x7F98000000000000, 0x202020202020202020202020202020202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x88), Broadcom BCM43xx 1.0 (5.10.131.36.15)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Corsair Force GS, 360,08 GB
Parallel ATA Device: HL-DT-ST DVDRW  GSA-S10N
USB Device: Built-in iSight, apple_vendor_id, 0x8501, 0xfd400000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8205, 0x1a100000 / 2
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0229, 0x5d200000 / 3
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0x5d100000 / 2
`

**Comment by sysfu** [comment]
I ran v0.2.4 via AppleScript Editor and it seemed to get farther, far enough to prompt me for the location of the .iso file.

**Comment by linusbobcat** [comment]
Could you guys test this version out? It contains the same script, although compiled/packaged in OS X Mavericks instead of El Capitan, sans the translations (although it's still clear what it does). https://drive.google.com/file/d/0B0MHDkAfdT90aDJHSUIyeHhEb1U/view?usp=sharing

**Comment by sysfu** [comment]
That version launches and prompts for an .iso file without crashing on OS 10.6.8

**Comment by gobr4ga** [comment]
Works fine on Lion

**Comment by linusbobcat** [comment]
Thank you so much for debugging this for me guys. I'll push out an update soon.

Edit: I pushed out the fix.
