### ISSUE TITLE
Doesn't work if USB is disk10 and above

### ISSUE THREAD

**Issue by lookitsatravis** [linusbobcat/create-elementary-os-installer#30]
After selecting the .iso, and choosing my USB by name, I'm getting the following error:

<img width="421" alt="screen shot 2016-01-23 at 16 09 01" src="https://cloud.githubusercontent.com/assets/606978/12533110/a43b156c-c1eb-11e5-8160-6d4a80e0abcd.png">

What's weird is that the disk I've selected is not disk1. On my Mac, my USB is mounted as disk11. disk1 is a virtual partition created by enabling FileVault on my Mac. Disks 2 through 10 are images mounted by the OS for one reason or another. So, my device is disk11.

Anything I can try? Or is this a legitimate bug?

**Comment by linusbobcat** [comment]
I just tested this by mounting an additional 10 disk images and forcing the USB drive to be 11. It looks like there's an error on my part with the script not liking disks above 10. I'll make a fix soon. In the meantime you might want to use the command line to create an elementary OS USB. Just do:

`sudo dd if=/location/of/iso of=/dev/rdisk(disknumber) bs=1m` 

Make sure you note the correct disknumber, or else you might risk wiping your hard drive.

Your situation does sound quite odd. The USB drive being the second device attached should be disk2, not disk11 (with Filevault).

**Comment by lookitsatravis** [comment]
Thanks a ton. Yeah, it's strange. It looks like 2 through 10 are images due to my pending OS update which I haven't completed.

Sorry for the bizarre edge case!

**Comment by linusbobcat** [comment]
No worries. As elementary OS gets more popular the only thing I expect is getting even more edge cases I'll have to fix.
