### ISSUE TITLE
Write copy and open up strings for Translations

### ISSUE THREAD

**Issue by linusbobcat** [linusbobcat/create-elementary-os-installer#33]
This blueprint tracks areas which could use/need copy and updated translations as well as some features that involve text.
## Shared
- "ContinueAnyway", used for buttons.
- "NonZeroExit", the localized version of this error is required in order to suppress it.
- "Copyright", literally just the word "copyright". I'll use this string along with the translated name to generate a localized plist.
## Create elementary OS Installer
- "NewOSXWarning", warns the user that it's best to use a newer version of the app.
- "PPCWarning", warns that the elementary OS doesn't support PPC, but that the disk can still be used on PCs and supported Macs.
- "OldMacWarning", warns that the Mac might not be able to boot USB drives.
- "XServeWarning", warns that XServe is unsupported.
- "ReformatDisk", tells the user that the disk is being reformatted
- "ConfirmQuit", warns before quitting progress on El Capitan and higher.
- "CopyingISO", the status on the progress bar that says that it's doing something. It should give a warning that this could take a while, and that it's highly advisable not to quit.
## Restore USB Drive
- "LocalizedUSBDriveName", the default name _Restore USB Drive_ will use. It will avoid using unicode characters when possible.
- "NameUSBDrive", the dialog text that says "what would you like to name your USB drive?"
## Frugal Installer
- "OldOSXWarning", warn that this tool only supports OS X Yosemite and higher. Lower versions apparently can't mount Linux ISOs. 
- "DiskNotPartitioned", warns that the disk hasn't been partitioned correctly.
## Translator's notes
- Note that "Create elementary OS Installer", "Restore USB Drive", and "Disk Utility should be translated, but that "Linux Mac USB Creator" shouldn't.
- Note that "NonZeroExit" doesn't have to be translated if one does not have access to a Mac. Note that "TranslatorTester" is required in order to get the string.

**Comment by TraderStf** [comment]
Hello,
Where to translate them?
I have checked, some are missing (in FR) 'OldMacWarning', 'PPCWarning' for example.

**Comment by linusbobcat** [comment]
Don't worry about this. This issue is a sort of meta-bug report for myself as a way to track my own development. I'm adding a bunch of features and opening a bunch of strings to translations instead of having them hardcoded. I'm also moving translations to Transifex and will have to get that set up.

**Comment by TraderStf** [comment]
OK :)

Few links I had compile but it is not yet finished or curated

Servers

https://github.com/translate/pootle
updated 2015-10
LOCALIZATION, not just translation


Apps

http://poedit.net	for mac
updated: 2015-10-21
pro = 20$

OmegaT - multiplatform CAT tool
The free computer aided translation (CAT) tool for professionals
http://sourceforge.net/projects/omegat/
Windows, Mac, Linux
updated 2015-10

http://omegat.sourceforge.net/manual-standard/en/chapter.installing.and.running.html#MAC.OSX.users

OmegaT Scripts download | SourceForge.net
Third-party scripts to be used with OmegaT CAT tool 

OmegaT.org



Info

XLIFF (XML Localisation Interchange File Format) converter



Other Resources

https://en.wikipedia.org/wiki/Category:Software-localization_tools

The Localization Tool | Articles around software localization with Sisulizer by its users, friends, and makers


https://poeditor.com/
FREE 1000 strings
formats: apple strings, xliff and xml - Linux, Windows and .json


Weblate - traduction sur le web
OS free

crowdin.net
Free for OS and Academic

Lokaligo — Online localization management platform for mobile apps
ios only
free 4 languages

Translate and Localize Android Applications | AndroGlot



http://sourceforge.net/directory/development/translation/os%3Amac/freshness%3Arecently-updated/?sort=update

http://zanata.org
2015-10

https://developer.apple.com/internationalization/
AppleGlot is a tool for extracting text strings to be translated and then merging them back into the localized application environment. It supports incremental localization.
AppleGlot 4.0 supports Interface Builder 2.0, 3.0, 4.0 and 5.0 style XIB, NIB and storyboard formats via ibtool.
Jan 25, 2013

Linqapp

transifex.netwww.transifex.net

launchpad.net



translationcloud.netwww.translationcloud.net

http://translatewiki.net/wiki/Ma...

www.oneskyapp.com


http://www.otrance.org

www.project-open.com

lokali.seLocalize your app in team

www.globalsight.com


$$$
Xliff Editor v.1.0 
Xcode localisation made easy!
Xliff Editor provides the easiest way of editing your XLIFF files. No more messing around with the XML format, worrying about file corruption. And you can forget about remembering to save, as every change you make is automatically saved for you.


Application externalisée, sociale et collaborative et traduction de site web - Get Localization
$$$

Gengo - Professional Translation Services by Gengo
$$$

**Comment by linusbobcat** [comment]
@TraderStf Woah there man. I’m definitely not going to use professional translation services and the lot.

I’m just moving to a basic Transifex service using community translations. Applescript already provides translation support and the current model of PRs works decently, although Transifex makes  it much more easier and will hopefully lower the barriers as well.

I appreciate your effort, but these are not things I need.

 I’m also going to delete your comment, not because I don’t like you, but rather because it’s easier to scroll on mobile. Please don’t take it personal.

**Comment by TraderStf** [comment]
no problemo, some offer free up to ## strings, if transifex is ok for you. thanks.
