### ISSUE TITLE
Installer wipes entire USB drive even if single partition is selected

### ISSUE THREAD

**Issue by pkirkovsky** [linusbobcat/create-elementary-os-installer#46]
### Steps:
1. Create a USB drive with more than 1 partition
2. Launch installer and select one the partitions as the target
3. Run installer
### Expected:

Installer installs ElementaryOS onto the selected partition _only_.
Installer makes it clear what actions will be performed.
### Actual:

Installer overwrites entire drive without warning!

**Comment by linusbobcat** [comment]
Unfortunately the method used to create bootable USB drives requires the whole drive to be wiped. I'm sorry that this happened to you. You could use something like Photorec (don't let the title fool you) to try to get out as many deleted files as possible. I'll add a warning when a USB drive contains multiple partitions.
- Linus Bobcat
