### ISSUE TITLE
AMD64 works I386 doesn't

### ISSUE THREAD

**Issue by pjpreilly** [linusbobcat/create-elementary-os-installer#58]
The amd64 elementary iso works fine but the I386 doesn't. 
elementaryos-0.3.2-stable-i386.20151209.iso
elementaryos-0.3.2-stable-amd64.20151209.iso
0.2.9-snowleopard tested on 64 macbook 3,1 & 32 macbook 1,1

**Comment by pjpreilly** [comment]
....os x Lion on the 64 & os x SL on the 32.

**Comment by linusbobcat** [comment]
How far can you go before it fails?

**Comment by pjpreilly** [comment]
It says it builds just like the 64 iso...the result usb are formatted differently. The 64 has the small efi partition? the 32 has one partiton which is iso 9660 Rockridge.

**Comment by pjpreilly** [comment]
![screen shot 2016-03-18 at 1 14 57 am](https://cloud.githubusercontent.com/assets/10430084/13869091/f10718d8-eca6-11e5-9b47-1d0e600225d3.png)

**Comment by pjpreilly** [comment]
![screen shot 2016-03-18 at 1 16 38 am](https://cloud.githubusercontent.com/assets/10430084/13869099/1e8db186-eca7-11e5-9064-ea44720f0510.png)

**Comment by pjpreilly** [comment]
Those last 2 are the 32 iso disk snapshots.

**Comment by pjpreilly** [comment]
Let me know if u need a tester or more info.

**Comment by linusbobcat** [comment]
I haven't tested with the latest ISO yet, but anything older than OS X Yosemite should result in a USB drive that's unreadable by OS X, which is normal behaviour.

This app simply copies the contents of the ISO to the USB drive using `dd` and doesn't do anything that modifies the filesystem type, apart from the step prior to copying where it reformats the USB drive to fat32.

How does the 32bit one not work? Does it not show up in the Mac boot picker unlike the 64bit one?

**Comment by pjpreilly** [comment]
Exactly....It's not bootable in the picker. I tried it on both the 64 & 32 bit macbook w/ the same results.

**Comment by linusbobcat** [comment]
Do either of them _show up_ at all in the picker, or does booting fail after selecting them?

I forgot to mention that old Macs, which includes your model, has difficulties booting elementary OS USB drives. I made a wiki page that [explains this](https://github.com/linusbobcat/create-elementary-os-installer/wiki/Older-Macs) in more depth.

**Comment by pjpreilly** [comment]
The 64 shows up & boots fine (64 only). The 32 doesn't show on either machine. It should show on both & boot on both I figure.

**Comment by pjpreilly** [comment]
Do u have a download link to a different 32 iso you want me to try? A 32 luna?

**Comment by linusbobcat** [comment]
Ah, elementary OS is currently missing 32bit EFI support. 

Just two more things:
- Did you create this bug report just to inform me of this issue but are currently fine to use the 64bit version, or because you need the 32bit version for some reason?
- Could you show me the System Information with Hardware Overview. Use the Grab app and select "Capture -> Selection" to grab everything but the serial and the hardwae UUID.

**Comment by pjpreilly** [comment]
I was hopin to us the 32 on the 32.
[system.tiff.zip](https://github.com/linusbobcat/create-elementary-os-installer/files/179125/system.tiff.zip)

**Comment by pjpreilly** [comment]
I had to zip it it wouldn't take tiff.

**Comment by pjpreilly** [comment]
The 32 has been abandoned by Apple, Google & now Mozilla. Linux is the last hope for a lot of good Apple hardware.

**Comment by pjpreilly** [comment]
The 64 is just about in the same boat.

**Comment by linusbobcat** [comment]
Creating a DVD based installer should work on older 32bit Macs. The lack of 32bit EFI is a bug on elementary's end which I can't fix. 

I'm going to close this issue as it doesn't relate to this project, but thanks for this information as it's hard to get information for which Mac does/does not support USB based booting.

**Comment by pjpreilly** [comment]
Installing refit then installing elementary over the os x install should work?

**Comment by linusbobcat** [comment]
If you install rEFIt on OS X, and overwrite the OS X partition, you will lose rEFIt. This is unless you install it on the EFI partition. Also note that it's not possible to boot 32bit elementary OS in EFI mode, you'll have to either use the 64bit version or boot it in emulated BIOS mode.

Your MacBook1,1 (and all other 32bit Intel Macs) will also only probably allow booting Linux from a DVD drive. 

I would recommend using rEFInd, the maintained fork, over rEFIt.

I'm unable to give help beyond that.
