### ISSUE TITLE
USB key becomes read only after using elementary os installer.

### ISSUE THREAD

**Issue by ragulbalaji** [linusbobcat/create-elementary-os-installer#7]
I install elementary os with this installer a few days ago, but now I want to reformat the usb key to store files but it has now become read only, I need help to reformat to FAT32.

http://i.imgur.com/evqjb34.jpg

**Comment by linusbobcat** [comment]
The method used to create the elementary OS installer does indeed create a non-persistent read-only USB drive. Unfortunately there's little I can do about this. You can reformat it to FAT 32 using disk utility, by using either the "Partition" or "Erase" functions. Both will erase elementary OS from the USB drive however.

**Comment by linusbobcat** [comment]
It looks like someone is having a similar issue. This is indeed a bug. I'm tracking progress from #9

**Comment by linusbobcat** [comment]
Do the following to restore the drive trough the command line:

first, use `diskutil list` to find your drive. It should say something like /dev/disk2 with the actual drive name beneath. Do not mess this up as a mistake can nuke your drive.

Then do this

  `diskutil erasevolume JHFS+ untitled /dev/disk2`

 Where "JHFS+" is the partition format, "untitled" is the name the drive will end up having in Finder, and "dev/disk2" is the disk identifier from above/

**Comment by ragulbalaji** [comment]
SOLVED THIS ISSUE by formatting using an old Windows XP PC than disk utility can reformat the disk.
