### ISSUE TITLE
USB Drives can't be reformatted in El Capitan

### ISSUE THREAD

**Issue by VincenMontagna** [linusbobcat/create-elementary-os-installer#9]
I'm trying to get to use my USB but there's no way to do so. Tried with Terminal and nothing. Even submitted the problem to Apple: https://discussions.apple.com/message/29443865#29443865

Help!

<img width="512" alt="2015-12-10 03 30 23 pm" src="https://cloud.githubusercontent.com/assets/9327078/11728304/47d4a084-9f5b-11e5-954d-fb41a33e84fb.png">
<img width="904" alt="2015-12-10 03 30 30 pm" src="https://cloud.githubusercontent.com/assets/9327078/11728306/47d84a0e-9f5b-11e5-9e57-25dac74e4c84.png">
<img width="825" alt="2015-12-10 04 29 55 pm" src="https://cloud.githubusercontent.com/assets/9327078/11728307/47ddd050-9f5b-11e5-9efe-d9e48ca7a227.png">

**Comment by linusbobcat** [comment]
Thanks for your bug report. I'll look into this. It looks like a few people have this issue.

**Comment by linusbobcat** [comment]
What terminal commands did you try using?

**Comment by VincenMontagna** [comment]
sudo diskutil reformat /dev/disk2 and diskutil repairDisk /dev/disk2

**Comment by linusbobcat** [comment]
Did you create the elementary OS installer on El Capitan or not? So far I ran into a new bug where it doesn't even work there.

**Comment by VincenMontagna** [comment]
Yup, did with El Capitan.

**Comment by linusbobcat** [comment]
In the meantime, if you have access to an older version of OS X or Disk Utility, use that to reformat the disk.

**Comment by linusbobcat** [comment]
the command `diskutil erasevolume JHFS+ drivename /dev/disk2` worked for me. Where "JHFS+" is the partition format, and "drivename" is the name the drive will end up having in Finder.

Edit: I might end up creating a small utility for restoring drives.

**Comment by VincenMontagna** [comment]
Will try right now. Thanks!

EDIT: It worked. Thanks!

**Comment by linusbobcat** [comment]
Please don't close this. This is still a bug I'll still need to fix. The terminal command is only a workabout.

**Comment by linusbobcat** [comment]
Created a build in tool for restoring USB drives.

**Comment by ragulbalaji** [comment]
@linusbobcat @VincenMontagna I filed a previous issue #7 as well, maybe you wanna look into that, I had to use Win XP PC reformat the usb thumb drive

**Comment by linusbobcat** [comment]
Your issue should have been identical to this one. I've updated the app to also include a reformater tool. OS X Yosemite and below, and other platforms should have no problem formatting resulting drives.
